#!/usr/bin/env bash
set -euo pipefail

mkdir -p \
  constitucion \
  reglamentos \
  reglamentos/reglamento-cff \
  reglamentos/reglamento-isr \
  reglamentos/reglamento-iva \
  reglamentos/reglamento-ieps \
  reglamentos/reglamento-ley-aduanera \
  reglamentos/reglamento-lss \
  tratados-internacionales \
  tratados-internacionales/convenios-doble-imposicion \
  tratados-internacionales/acuerdos-intercambio-informacion \
  tratados-internacionales/beps-ocde \
  leyes-federales \
  leyes-federales/codigo-fiscal-de-la-federacion \
  leyes-federales/ley-del-isr \
  leyes-federales/ley-del-iva \
  leyes-federales/ley-del-ieps \
  leyes-federales/ley-aduanera \
  leyes-federales/ley-de-ingresos-de-la-federacion \
  leyes-federales/ley-federal-de-derechos \
  leyes-federales/ley-de-coordinacion-fiscal \
  leyes-federales/ley-de-comercio-exterior \
  leyes-federales/ley-del-seguro-social \
  leyes-federales/ley-del-infonavit \
  leyes-federales/ley-del-issste \
  leyes-federales/ley-general-de-sociedades-mercantiles \
  leyes-federales/ley-del-mercado-de-valores \
  leyes-federales/ley-general-titulos-operaciones-credito \
  leyes-federales/ley-de-los-sistemas-de-ahorro-para-el-retiro \
  leyes-federales/ley-antilavado-lfpiorpi \
  leyes-federales/ley-federal-derechos-del-contribuyente \
  leyes-federales/ley-federal-procedimiento-contencioso-administrativo \
  resolucion-miscelanea-fiscal \
  resolucion-miscelanea-fiscal/2024 \
  resolucion-miscelanea-fiscal/2024/modificaciones \
  resolucion-miscelanea-fiscal/2024/anexos \
  resolucion-miscelanea-fiscal/2025 \
  resolucion-miscelanea-fiscal/2025/modificaciones \
  resolucion-miscelanea-fiscal/2025/anexos \
  criterios-sat \
  criterios-sat/normativos \
  criterios-sat/no-vinculativos \
  criterios-sat/internos \
  jurisprudencia \
  jurisprudencia/scjn \
  jurisprudencia/tfja \
  jurisprudencia/tcc \
  scripts

touch \
  constitucion/.gitkeep \
  reglamentos/.gitkeep \
  reglamentos/reglamento-cff/.gitkeep \
  reglamentos/reglamento-isr/.gitkeep \
  reglamentos/reglamento-iva/.gitkeep \
  reglamentos/reglamento-ieps/.gitkeep \
  reglamentos/reglamento-ley-aduanera/.gitkeep \
  reglamentos/reglamento-lss/.gitkeep \
  tratados-internacionales/.gitkeep \
  tratados-internacionales/convenios-doble-imposicion/.gitkeep \
  tratados-internacionales/acuerdos-intercambio-informacion/.gitkeep \
  tratados-internacionales/beps-ocde/.gitkeep \
  leyes-federales/.gitkeep \
  leyes-federales/codigo-fiscal-de-la-federacion/.gitkeep \
  leyes-federales/ley-del-isr/.gitkeep \
  leyes-federales/ley-del-iva/.gitkeep \
  leyes-federales/ley-del-ieps/.gitkeep \
  leyes-federales/ley-aduanera/.gitkeep \
  leyes-federales/ley-de-ingresos-de-la-federacion/.gitkeep \
  leyes-federales/ley-federal-de-derechos/.gitkeep \
  leyes-federales/ley-de-coordinacion-fiscal/.gitkeep \
  leyes-federales/ley-de-comercio-exterior/.gitkeep \
  leyes-federales/ley-del-seguro-social/.gitkeep \
  leyes-federales/ley-del-infonavit/.gitkeep \
  leyes-federales/ley-del-issste/.gitkeep \
  leyes-federales/ley-general-de-sociedades-mercantiles/.gitkeep \
  leyes-federales/ley-del-mercado-de-valores/.gitkeep \
  leyes-federales/ley-general-titulos-operaciones-credito/.gitkeep \
  leyes-federales/ley-de-los-sistemas-de-ahorro-para-el-retiro/.gitkeep \
  leyes-federales/ley-antilavado-lfpiorpi/.gitkeep \
  leyes-federales/ley-federal-derechos-del-contribuyente/.gitkeep \
  leyes-federales/ley-federal-procedimiento-contencioso-administrativo/.gitkeep \
  resolucion-miscelanea-fiscal/.gitkeep \
  resolucion-miscelanea-fiscal/2024/.gitkeep \
  resolucion-miscelanea-fiscal/2024/modificaciones/.gitkeep \
  resolucion-miscelanea-fiscal/2024/anexos/.gitkeep \
  resolucion-miscelanea-fiscal/2025/.gitkeep \
  resolucion-miscelanea-fiscal/2025/modificaciones/.gitkeep \
  resolucion-miscelanea-fiscal/2025/anexos/.gitkeep \
  criterios-sat/.gitkeep \
  criterios-sat/normativos/.gitkeep \
  criterios-sat/no-vinculativos/.gitkeep \
  criterios-sat/internos/.gitkeep \
  jurisprudencia/.gitkeep \
  jurisprudencia/scjn/.gitkeep \
  jurisprudencia/tfja/.gitkeep \
  jurisprudencia/tcc/.gitkeep \
  scripts/.gitkeep
